name: Comment lcov Code Coverage Report
description: Comments on a pull request with a lcov code coverage report
author: Steffen Koette
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: false
    default: ${{ github.token }}
  pr-number:
    description: Number of the Pull Request
    required: false
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  filter-changed-files:
    description: Set to true to only comment with coverage on files changed in this commit
    required: false
    default: false
  delete-old-comments:
    description: Set to true to delete old Coverage Report comments
    required: false
    default: false
  working-directory:
    description: Set working directory if project is not in root folder
    required: false
    default: "./"
  title:
    description: Title to add to the comment
    required: false
  hide-branch-coverage:
    description: Hides the branch coverage in the output if set to true
    required: false
  output-file:
    description: Filename to output result to, instead of posting a comment
    required: false


runs:
  using: node20
  main: dist/main.js
